### ISSUE TITLE
Проблемы, обнаруженные во время тестирования системы

### ISSUE THREAD

**Issue by Eset35** [Parol45/PolyTeX#14]
1) Ошибка при создании документа
![image](https://user-images.githubusercontent.com/37243389/84714974-e7042900-af77-11ea-9fd4-1400e9832c0b.png)
Ошибку можно исправить, например, так: 
![image](https://user-images.githubusercontent.com/37243389/84714992-f1262780-af77-11ea-90d0-f8a15bcdbf31.png)

2) Наблюдаю проблему с добавлением владельца к файлу, мне всегда выдает, что у пользователя уже максимально число файлов.
3) На мой взгляд не очень хорошее решение переводит в панель работы с документом при клике по строке таблицы(там где список документов). Логичнее было бы убрать эту возможность, а переход сделать только по нажатию по имени файла(первая ячейка строки).
4) В меню работы над проектом, если поле "имя нового файла" не заполнено, то нажатие кнопки "Создать" не дает никакого эффекта, возможно стоит добавить вывод ошибки. Аналогично с полем "имя новой папки"

**Comment by Parol45** [comment]
Благодарим за сообщение об этих проблемах.

Ошибки исправлены.
