### ISSUE TITLE
Неверный текст ошибки при добавлении владельца

### ISSUE THREAD

**Issue by Eset35** [Parol45/PolyTeX#15]
При добавлении к документу владельца, который был уже добавлен, текст ошибки говорит, что пользователь "Не найден", логичнее было бы информировать, что пользователь уже добавлен. 
![image](https://user-images.githubusercontent.com/37243389/84750162-9ca89980-afc3-11ea-998a-3bc37c3d2263.png)

**Comment by Parol45** [comment]
Благодарим за сообщение о проблеме.

Ошибка исправлена.
