### ISSUE TITLE
Отсутствует реакция на клик по кнопке "PolyTeX - LaTeX Editor"

### ISSUE THREAD

**Issue by Eset35** [Parol45/PolyTeX#16]
Мелкая недоработка.
Отсутствует реакция на клик по кнопке "PolyTeX - LaTeX Editor". 
Либо наведение на этот элемент не должно порождать никаких реакций(сейчас меняется фон), либо клик должен переводить на главную страницу.

**Comment by Parol45** [comment]
Выделение убрано.

P.S. красиво жи
