### ISSUE TITLE
Отсутствует проверка длины текста на некоторых полях.

### ISSUE THREAD

**Issue by Eset35** [Parol45/PolyTeX#17]
Поля "Имя проекта", "Имя пользователя" не содержат проверку длины введенного текста, и если ввести достаточно длинную строку, то при попытке создания проекта или добавления владельца файла появляется ошибка:
![image](https://user-images.githubusercontent.com/37243389/84787849-21f97180-aff7-11ea-8e85-9754574d31c1.png)

P.S. поля создания файла и папки это проблемы лишены, там есть проверка.

**Comment by Parol45** [comment]
Благодарим за сообщение о проблеме.

Ошибка исправлена.
